site_name: Documentall

theme:
  name: material
  logo: _static/img/logo.png
  favicon: _static/img/logo.png
  highlightjs: true
  hljs_languages:
    - yaml
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: home/index.md
  - Django:
    - Basic Commands: django/basic_commands.md